package com.example.Shoe_shop.exception;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(500,"Lỗi không xác định"),
    UNAUTHORIZED(401,"Bạn chưa đăng nhập, vui lòng đăng nhập"),
    FORBIDDEN(403,"Bạn không có quyền truy cập"),
    INVALID_MESSAGE_KEY(400,"Message key không hợp lệ"),
    USER_EXISTED(409,"Người dùng đã tồn tại"),
    ROLE_NOT_FOUND(404,"Vai trò không tồn tại"),
    EMAIL_EXISTED(409,"Email đã tồn tại"),
    PHONE_NUMBER_EXISTED(409,"Số điện thoại đã tồn tại"),
    USER_NAME_INVALID(400,"Tên người dùng không được để trống"),
    EMAIL_INVALID(400,"Email không hợp lệ"),
    PASSWORD_INVALID(400,"Mật khẩu phải có ít nhất 6 kí tự"),
    PHONE_INVALID(400,"Số điện thoại không được bỏ trống và phải có 10 số"),
    USER_NOT_FOUND(404,"Không tìm thấy người dùng"),
    PASSWORD_BLANK(400,"Mật khẩu không được để trống"),
    FULL_NAME_INVALID(400,"Họ tên không được để trống"),
    ADDRESS_INVALID(400,"Địa chỉ không được để trống"),
    CATEGORY_NOT_FOUND(400,"Không tìm thấy danh mục"),
    CATEGORY_NAME_INVALID(400,"Tên danh mục không được để trống"),
    CATEGORY_HAS_PRODUCTS(409,"Danh mục đang chứa sản phẩm"),
    BRAND_NAME_INVALID(400,"Tên thương hiệu không được để trống"),
    BRAND_NOT_FOUND(400,"Không tìm thấy thương hiệu"),
    BRAND_HAS_PRODUCTS(400,"Thương hiệu đang chứa sản phẩm"),
    PRODUCT_NAME_INVALID(400,"Tên sản phẩm không được để trống"),
    BRAND_ID_INVALID(400,"Mã thương hiệu không được để trống"),
    CATEGORY_ID_INVALID(400,"Mã danh mục không được để trống"),
    SIZE_INVALID(400,"Kích thước không được để trống"),
    COLOR_INVALID(400,"Màu sắc không được để trống"),
    REGULAR_PRICE_INVALID(400,"Giá gốc không được để trống"),
    REGULAR_PRICE_GREATER_THAN_0(400,"Giá gốc phải lớn hơn 0"),
    STOCK_INVALID(400,"Tồn kho không được để trống"),
    STOCK_QUANTITY_GREATER_THAN_0(400,"Số lượng tồn kho phải lớn hơn 0"),
    PRODUCT_ID_INVALID(400,"Mã sản phẩm không được để trống"),
    IMAGE_URL_INVALID(400,"Đường dẫn ảnh không được để trống"),
    PRODUCT_NOT_FOUND(404,"Không tìm thấy sản phẩm"),
    PRODUCT_ALREADY_DELETED(409,"Sản phẩm đã bị xóa"),
    USER_ALREADY_DELETED(409,"Người dùng đã bị xóa"),
    ALREADY_IN_WISHLIST(409,"Sản phẩm đã có trong danh sách yêu thích"),
    WISHLIST_NOT_FOUND(404,"Không tìm thấy danh sách yêu thích"),
    VARIANT_ID_REQUIRED(400,"Mã biến thể không được để trống"),
    QUANTITY_MIN_1(400,"Số lượng phải lớn hơn hoặc bằng 1"),
    CART_EMPTY(404,"Giỏ hàng trống"),
    PRODUCT_VARIANT_NOT_FOUND(404,"Không tìm thấy biến thể sản phẩm"),
    STOCK_NOT_ENOUGH(409,"Không đủ hàng trong kho"),
    FILE_EMPTY(400,"Tệp tải lên trống"),
    USER_ID_REQUIRED(400,"Mã người dùng không được để trống"),
    SHIPPING_ADDRESS_REQUIRED(400,"Địa chỉ giao hàng không được để trống"),
    PAYMENT_METHOD_REQUIRED(400,"Phương thức thanh toán không được để trống"),
    OUT_OF_STOCK(400,"Sản phẩm đã hết hàng"),
    TRACKING_NUMBER_BLANK(400,"Mã vận đơn không được để trống"),
    SHIPPING_METHOD_REQUIRED(400,"Phương thức vận chuyển không được để trống"),
    ORDER_ID_REQUIRED(400,"Mã đơn hàng không được để trống"),
    INVALID_STATUS_TRANSITION(400,"Chuyển trạng thái đơn hàng không hợp lệ"),
    ORDER_STATUS_IS_NOT_PENDING(400,"Chỉ đơn hàng đang ở trạng thái PENDING mới có thể hủy"),
    ORDER_NOT_FOUND(404,"Đơn hàng không tồn tại"),
    ORDER_NOT_PAYABLE(400,"Đơn hàng không thể thanh toán"),
    INVALID_SIGNATURE(400,"Chữ ký không hợp lệ"),
    PAYMENT_NOT_FOUND(404,"Không tìm thấy giao dịch thanh toán"),
    PAYMENT_ALREADY_SUCCESS(400,"Thanh toán đã thành công"),
    ORDER_CANNOT_BE_CANCELLED(400,"Đơn hàng không thể hủy"),
    ORDER_BY_COD_CANNOT_BE_CANCELLED(400,"Đơn hàng thanh toán COD không thể hủy do đã xử lý hoặc giao"),
    ORDER_BY_VNPAY_CANNOT_BE_CANCELLED(400,"Đơn hàng thanh toán VNPAY không thể hủy do đã xử lý hoặc giao"),
    PAYMENT_CANNOT_REFUND(400,"Thanh toán không thể hoàn tiền"),
    PAYMENT_METHOD_NOT_SUPPORT_REFUND(400,"Phương thức thanh toán không hỗ trợ hoàn tiền"),
    REFUND_FAILED(400,"Hoàn tiền thất bại, vui lòng thử lại"),
    USER_NOT_VERIFIED(400,"Người dùng chưa xác minh"),
    VERIFYCODE_NOT_FOUND(404,"Không tìm thấy mã xác minh"),
    PASSWORD_INCORRECT(400,"Mật khẩu không chính xác"),
    PASSWORD_MISMATCH(400,"Mật khẩu không khớp"),
    UNAUTHORIZED_ACTION(400,"Bạn không thể đổi mật khẩu của người dùng khác"),
    SHIPPING_METHOD_NOT_FOUND(404,"Không tìm thấy phương thức vận chuyển"),
    CART_ITEM_NOT_FOUND(404,"Không tìm thấy sản phẩm trong giỏ hàng"),
    PURCHASE_ORDER_NOT_FOUND(404,"Không tìm thấy đơn đặt hàng"),
    PURCHASE_ORDER_ITEM_NOT_FOUND(404,"Không tìm thấy mặt hàng đơn đặt hàng"),
    ;

    private final int code;
    private final String message;

}
