spring:
  application:
    name: Shoe_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nham3112@
    url: jdbc:mysql://localhost:3306/Shoe_Ecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
      enabled: true


server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: P+IPQo0w49hNbFHj9ZxKsXGwfyJNcGGcqEa/dl8dtQo=
  expiryHour: 1
  expiryDay: 14

app:
  upload:
    dir: uploads

vnpay:
#  tmnCode: ETZKPEHL
#  secretKey: YUZFYVVO04ETB2H97OQ970LT60EXNFTG
  tmnCode: MVX1TM4Y
  secretKey: A0MNUDBXHIO4X5XOCDGPQBMSG8A6K42B
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://8080/api/vnpay/vnpay-callback
  ipnUrl: https://sandbox.vnpayment.vn/vnpaygw-sit-testing/user/login
  version: 2.1.0

crm:
  usernamevnpay: "nguyenluong140504@gmail.com"
  passwordvnpay: "@Nguyenluong1405"
